/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as MyImagesRouteImport } from './routes/my-images'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyImagesIndexRouteImport } from './routes/my-images/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MyImagesTrashRouteImport } from './routes/my-images/trash'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminImagesRouteImport } from './routes/admin/images'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const MyImagesRoute = MyImagesRouteImport.update({
  id: '/my-images',
  path: '/my-images',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyImagesIndexRoute = MyImagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyImagesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MyImagesTrashRoute = MyImagesTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => MyImagesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImagesRoute = AdminImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/my-images': typeof MyImagesRouteWithChildren
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/style-guide': typeof StyleGuideRoute
  '/upload': typeof UploadRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/my-images/trash': typeof MyImagesTrashRoute
  '/admin/': typeof AdminIndexRoute
  '/my-images/': typeof MyImagesIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/style-guide': typeof StyleGuideRoute
  '/upload': typeof UploadRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/my-images/trash': typeof MyImagesTrashRoute
  '/admin': typeof AdminIndexRoute
  '/my-images': typeof MyImagesIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/my-images': typeof MyImagesRouteWithChildren
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/style-guide': typeof StyleGuideRoute
  '/upload': typeof UploadRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/my-images/trash': typeof MyImagesTrashRoute
  '/admin/': typeof AdminIndexRoute
  '/my-images/': typeof MyImagesIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/my-images'
    | '/recommendations'
    | '/register'
    | '/results'
    | '/search'
    | '/style-guide'
    | '/upload'
    | '/admin/dashboard'
    | '/admin/images'
    | '/admin/users'
    | '/my-images/trash'
    | '/admin/'
    | '/my-images/'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/recommendations'
    | '/register'
    | '/results'
    | '/search'
    | '/style-guide'
    | '/upload'
    | '/admin/dashboard'
    | '/admin/images'
    | '/admin/users'
    | '/my-images/trash'
    | '/admin'
    | '/my-images'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/my-images'
    | '/recommendations'
    | '/register'
    | '/results'
    | '/search'
    | '/style-guide'
    | '/upload'
    | '/admin/dashboard'
    | '/admin/images'
    | '/admin/users'
    | '/my-images/trash'
    | '/admin/'
    | '/my-images/'
    | '/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MyImagesRoute: typeof MyImagesRouteWithChildren
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  ResultsRoute: typeof ResultsRoute
  SearchRoute: typeof SearchRoute
  StyleGuideRoute: typeof StyleGuideRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-images': {
      id: '/my-images'
      path: '/my-images'
      fullPath: '/my-images'
      preLoaderRoute: typeof MyImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-images/': {
      id: '/my-images/'
      path: '/'
      fullPath: '/my-images/'
      preLoaderRoute: typeof MyImagesIndexRouteImport
      parentRoute: typeof MyImagesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/my-images/trash': {
      id: '/my-images/trash'
      path: '/trash'
      fullPath: '/my-images/trash'
      preLoaderRoute: typeof MyImagesTrashRouteImport
      parentRoute: typeof MyImagesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/images': {
      id: '/admin/images'
      path: '/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminImagesRoute: typeof AdminImagesRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminImagesRoute: AdminImagesRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MyImagesRouteChildren {
  MyImagesTrashRoute: typeof MyImagesTrashRoute
  MyImagesIndexRoute: typeof MyImagesIndexRoute
}

const MyImagesRouteChildren: MyImagesRouteChildren = {
  MyImagesTrashRoute: MyImagesTrashRoute,
  MyImagesIndexRoute: MyImagesIndexRoute,
}

const MyImagesRouteWithChildren = MyImagesRoute._addFileChildren(
  MyImagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MyImagesRoute: MyImagesRouteWithChildren,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  ResultsRoute: ResultsRoute,
  SearchRoute: SearchRoute,
  StyleGuideRoute: StyleGuideRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
